djangotweet/djangotweet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweetapp.urls')),

]

djangotweet/tweetapp/urls.py
from django.urls import path
from .import views

app_name = 'tweetapp'

urlpatterns = [
    path('',views.listtweet, name='listtweet'),
    path('addtweet/',views.addtweet, name='addtweet'),
    path('addtweetbyform/',views.addtweetbyform, name='addtweetbyform'),
    path('addtweetbymodelform/',views.addtweetbymodelform, name='addtweetbymodelform'),
]

djangotweet/tweetapp/models.py
from django.db import models

# Create your models here.

class Tweet(models.Model):
    nickname = models.CharField(max_length=30)
    message = models.CharField(max_length=280)

    def __str__(self):
        return f"Tweet nick: {self.nickname} message: {self.message}"

djangotweet/tweetapp/views.py
from django.shortcuts import redirect, render
from . import models
from django.urls import reverse
from .froms import AddTweetForm, AddTweetModelForm
# Create your views here.

def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict = {'tweets': all_tweets}
    return render(request, 'tweetapp/listtweet.html', context=tweet_dict)

def addtweet(request):
    if request.method == "POST":
        nickname = request.POST.get("nickname")
        message = request.POST.get("message")
        models.Tweet.objects.create(nickname=nickname, message=message)
        return redirect(reverse('tweetapp:listtweet'))
    else:
        return render(request, 'tweetapp/addtweet.html')
    
def addtweetbyform(request):
    if request.method == "POST":
            form=AddTweetForm(request.POST)
            if form.is_valid():
                nickname=form.cleaned_data['nickname']
                message=form.cleaned_data['message']
                return redirect(reverse('tweetapp:listtweet'))
            
            else:   
                print("error in form")     
                return render(request, 'tweetapp/addtweetbyform.html', context={'form':form})

        
    else:
        form=AddTweetForm()
        return render(request, 'tweetapp/addtweetbyform.html', context={'form':form})
    

def addtweetbymodelform(request):
    if request.method == "POST":
        form=AddTweetModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('tweetapp:listtweet'))
        else:
            print("error in form")
            return render(request, 'tweetapp/addtweetbymodelform.html', context={'form':form})
    else:
        form=AddTweetModelForm()
        return render(request, 'tweetapp/addtweetbymodelform.html', context={'form':form})

djangotweet/templates/base.html
{% load static %}
<html lang="en" >


<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <title>Tweet App</title>  
  <link rel="stylesheet" href="{% static 'tweetapp/customform.css' %}">

</head>


<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'tweetapp:listtweet'%}">Tweet App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tweetapp:addtweet' %}">Add Tweet</a>
        </li>
        <!--
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tweetapp:addtweetbyform' %}">Add Tweet By Form</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tweetapp:addtweetbymodelform' %}">Add Tweet By Model Form</a>
        </li>
        -->
      </ul>
    </div>
  </div>
</nav>


{% block content %}

{% endblock %}



</body>
</html>

djangotweet/tweetapp/templates/tweetapp/addtweet.html
{% extends 'base.html' %}

{% block content %}


<form action="" method="post">
    {% csrf_token %}
    <div class="container" style="width: 50%;">


      <div class="mb-3">
    <label for="nickname" class="form-label">Nickname</label>
    <input type="text" class="form-control" id="nickname" name="nickname">
  </div>
  <div class="mb-3">
    <label for="message" class="form-label">Message</label>
    <input type="text" class="form-control" id="message" name="message">
  </div>
  <button type="submit" class="btn btn-primary">Send Tweet</button>
</div>
</form>





{% endblock %}

djangotweet/tweetapp/templates/tweetapp/addtweetbyform.html
{% extends 'base.html' %}

{% block content %}
<h1>AddTweetByForm</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="btn btn-primary">Send Tweet</button>
 
</form>





{% endblock %}

djangotweet/tweetapp/templates/tweetapp/addtweetbymodelform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Add Tweet By Model Form</h1>

<div class="container tweetfrom">
<form action="" method="post">
    {% csrf_token %}


    {% for field in form %}
        <div class="mb-3">
            {{ field.label_tag }} 
            {{ field }}
            </div>

        {% endfor %}



    <button type="submit" class="btn btn-primary">Send Tweet</button>

</form>
</div>






{% endblock %}

djangotweet/tweetapp/templates/tweetapp/listtweet.html
{% extends 'base.html' %}

{% block content %}


    <div class="container" style="width:%50;">
        
    {% for tweet in tweets %}
    <div class="card" style="padding:10px;">
        <div class="card-header" style="background-color:cornflowerblue;">
            <h4>{{ tweet.nickname }}</h4>
            </div>
        <div class="card-body">
           <p class="card-text">{{ tweet.message }}</p>
        </div>
 

</div>
    {% endfor %}
    


</div>
{% endblock %}